### PR TITLE
Added full cmake support.

### PR DESCRIPTION
**Pull request by liarokapisv**
Hi there, I added modern cmake support to the project. This means the build scripts are no longer needed and the library can be built in a lot different build configurations. By having proper cmake support we have access to all of cmake's machinary for library discovery which means we automatically get package manager integration. The package can currently work with any package manager that provides config files for the dependencies. Currently tested with vcpkg and conan although vcpkg has better out of box support for the specific dependencies. Since we have package manager integration it is no longer necessary to supply dependencies for windows or pollute the system with the library dependencies. 

A few more things: 

I added registry support to cmake which means one may use vcpkg to retrieve the dependencies then build and the package immediately becomes available to cmake's find_package machinary. No need to system install or use the package manager on dependent projects.

If system installing the library one will have to use a package manager with the dependent library so as to supply the proper targets. This is to be expected since library locations may change between systems so one can't reuse the original configuration to detect cmake targets.

I also changed the project structure a bit. Since the library can now be system installed I thought it would be better to have a proper sgg/* header structure so as to not mess with any system-wide graphics* headers.

See new README.md for details.

### CODE REVIEW

**Comment by liarokapisv** [comment]
If agreed to merge I would like to perform a few more changes in order to also seemlessly support the native unix package managers. It's just a bit more work to match the different target names.

**Comment by ViNeek** [comment]
Hi @liarokapisv. This looks like a great PR.
I will need some time to review this. Please send me an e-mail so we can stay in contact.
Thank you for the help.

**Comment by liarokapisv** [comment]
The original PR used targets only compatible with vcpkg. This meant that it did not allow for system-wide library autodetection so the linux example on the docs wouldn't work. The latest commit adds support by wrapping available vcpkg, cmake and project native find modules and config files. System-wide installations on a relative new debian machine and windows should work fine. No vcpkg needed. In fact we allow one to build the libary with or without vcpkg and consumers can themselves either use the native libraries or the vcpkg supplied libraries independently. Tested on Mint 20 with both vcpkg and system-wide installations and on Windows 10 with vcpkg only.

**Comment by liarokapisv** [comment]
Made the following changes as discussed on email, squashed and rebased to main so as to improve patch readability:

- reverted to old singular folder for both sources and header files.
- changed graphics folder to sgg.
- modified scripts so as to use the new folder name and root folder include path.
- changed instructions to only showcase usage of static libraries instead of shared in order to not have students deal with dynamic linking on windows. When using shared linking vcpkg automatically downloads dlls to executable folder so this is not as bad as it could be but it still forces consumers to use the vcpkg toolchain or add vcpkg's lib directory to PATH.

It would be a good idea to double-check the changed build scripts since I only tested the script changes on linux.
Kind regards.

**Comment by iliaskap12** [comment]
Hello there. I needed CMake support to use the library in my CLion project. Since I couldn't figure out on my own how to make the appropriate cmake files, I forked the this repo, and found a way to get this open pull request as well. I finally managed to get it working with my CLion project but I ran into these issues:

1. The $VCPKG_INSTALL_DIR could not find on each own the vcpkg install directory, so I had to replace it with an absolute path.
2. CMake was trying to add the to the target (project) libsgg.a, but was looking for it inside sgg/build, while it stored into sgg/lib. I couldn't find what command instructed CMake to look there, so I just copied libsgg.a and libsggd.a into build directory as well and it solved the problem.

I thought it was appropriate to comment these issues here in case they need to be fixed. My machine is running Ubuntu 20.10. 
Thank you for this awesome integration.
Kind regards.

**Comment by liarokapisv** [comment]
> Hello there. I needed CMake support to use the library in my CLion project. Since I couldn't figure out on my own how to make the appropriate cmake files, I forked the this repo, and found a way to get this open pull request as well. I finally managed to get it working with my CLion project but I ran into these issues: ...
> 

Hi there, the VCPKG_INSTALL_DIR on the docs was just a placeholder, one needs to replace with the actual path. I should probably makes this more clear. I am not sure why your project looked at sgg/lib for the static library. Could it be that you specified a wrong build directory when first configuring with registry support? There should be a symlink-like file at ~/.cmake/* containing the folder.

**Comment by iliaskap12** [comment]
> > Hello there. I needed CMake support to use the library in my CLion project. Since I couldn't figure out on my own how to make the appropriate cmake files, I forked the this repo, and found a way to get this open pull request as well. I finally managed to get it working with my CLion project but I ran into these issues:
> > 
> > 1. The $VCPKG_INSTALL_DIR could not find on each own the vcpkg install directory, so I had to replace it with an absolute path.
> > 2. CMake was trying to add the to the target (project) libsgg.a, but was looking for it inside sgg/build, while it stored into sgg/lib. I couldn't find what command instructed CMake to look there, so I just copied libsgg.a and libsggd.a into build directory as well and it solved the problem.
> > 
> > I thought it was appropriate to comment these issues here in case they need to be fixed. My machine is running Ubuntu 20.10.
> > Thank you for this awesome integration.
> > Kind regards.
> 
> Hi there, the VCPKG_INSTALL_DIR on the docs was just a placeholder, one needs to replace with the actual path. I should probably makes this more clear. I am not sure why your project looked at sgg/lib for the static library. Could it be that you specified a wrong build directory when first configuring with registry support? There should be a symlink-like file at ~/.cmake/* containing the folder.

Cool, initially I thought the VCPKG_INSTALL_DIR was a CMake macro command. As for the second issue, I might have not explained it thoroughly. The problem wasn't that my project looked for the static library in the sgg/lib folder, because it didn't. It looked for it as it should in the sgg/build folder. The problem was that after I ran the build script the static library wasn't there, but instead resided in the sgg/lib folder, essentially making it unable for CMake to find it. That's why I had to manually copy the static libraries from sgg/lib to sgg/build. To elaborate, here is the folder structure of the sgg library after I ran the build script:

sgg
├── 3rdparty
│   ├── assets
│   ├── bin
│   ├── include
│   │   ├── freetype
│   │   │   ├── config
│   │   │   └── internal
│   │   │       └── services
│   │   ├── GL
│   │   ├── glm
│   │   │   ├── detail
│   │   │   ├── gtc
│   │   │   └── gtx
│   │   └── SDL2
│   └── lib
├── assets
├── build
│   ├── CMakeFiles
│   │   ├── 3.19.2
│   │   │   └── CompilerIdCXX
│   │   │       └── tmp
│   │   ├── CheckLibraryExists
│   │   ├── CMakeTmp
│   │   ├── demo.dir
│   │   │   └── demo
│   │   ├── Export
│   │   │   └── share
│   │   │       └── cmake
│   │   │           └── sgg
│   │   ├── sgg.dir
│   │   │   └── sgg
│   │   └── uninstall.dir
│   ├── Debug
│   │   └── sgg
│   ├── Release
│   │   └── sgg
│   └── share
├── cmake
├── demo
├── docs
├── doxygen
│   └── images
├── lib
│   ├── libsgg.a
│   └── libsggd.a
└── sgg

As you can see, originally, after I ran the build script the static libraries weren't under the build folder, where CMake looked them up, but instead under the lib folder. Just for the record, I didn't change the configuration in any way, I ran the CMake build command as it is in the README.md file. Hope that helped clarify the issue.

Respectfully,
- Ilias

**Comment by liarokapisv** [comment]
This very weird, cmake should not be outputting anything outside of the build directory. 

Also can't reproduce on ubuntu 18.04. There is no lib folder after building and everything is as should be in the build folder.

I guess that since you are on Ubuntu you also changed the triplets on the command line arguments to x64-linux or similar. 

Are you running from the command line or through Clion? 
Could you delete the build folder, perform the procedure again and post the output of the build command with VERBOSE set ? 

eg:
`VERBOSE=1 cmake --build build`

Thanks a lot for reporting this!

**Comment by iliaskap12** [comment]
I made some progress with your advice but still the libraries needed were not found. Firstly, let me start by saying that I hadn't changed the registries, as I wasn't sure what they were doing and I didn't want to mess with them. I changed them now to x64-linux as suggested but it didn't seem to affect the build any how. Secondly, the sgg/lib folder was there not because of CMake, but because I had ran before the build script provided with the library (`sh ./sgg/build_sgg_x_64.sh`). I deleted the sgg/build and the sgg/lib directory and tested with the following test cases:

- Run the build script and then the cmake build command without changing the registries
```
$ cd sgg
$ sh ./build_sgg_x64.sh
$ cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_PACKAGE_REGISTRY=ON -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
```
- Run the build script and then the cmake build command with changing the registries (x64-linux)
```
$ cd sgg
$ sh ./build_sgg_x64.sh
$ cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_PACKAGE_REGISTRY=ON -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
```
- Run the cmake build command with changing the registries and without running the build script
```
$ cd sgg
$ cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_PACKAGE_REGISTRY=ON -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
```

After each test case I run in the terminal the following, hoping to find anywhere in the folder structure the static libraries:
```
tree sgg -P "*libsgg*"
find ~/sgg/ -iname "*libsgg*"
sudo find ~/sgg/ -iname "*libsgg*"
```

The result was the same every time, the static libraries weren't found.
The folder structure was this:

```
sgg
├── 3rdparty
│   ├── assets
│   ├── bin
│   ├── include
│   │   ├── freetype
│   │   │   ├── config
│   │   │   └── internal
│   │   │       └── services
│   │   ├── GL
│   │   ├── glm
│   │   │   ├── detail
│   │   │   ├── gtc
│   │   │   └── gtx
│   │   └── SDL2
│   └── lib
├── assets
├── build
│   ├── CMakeFiles
│   │   ├── 3.19.2
│   │   │   └── CompilerIdCXX
│   │   │       └── tmp
│   │   ├── CheckLibraryExists
│   │   ├── CMakeTmp
│   │   ├── demo.dir
│   │   │   └── demo
│   │   ├── Export
│   │   │   └── share
│   │   │       └── cmake
│   │   │           └── sgg
│   │   ├── sgg.dir
│   │   │   └── sgg
│   │   └── uninstall.dir
│   └── share
├── cmake
├── demo
├── docs
├── doxygen
│   └── images
└── sgg
```

All of these were ran through the command line terminal (not the IDE terminal).

The CMakeLists.txt file of my project is the following:

```
cmake_minimum_required(VERSION 3.17)
project(1942_berlin VERSION 1.0.0)

set(CMAKE_CXX_STANDARD 20)

find_package(sgg REQUIRED)

set(CMAKE_CURRENT_SOURCE_DIR src)
add_executable(${PROJECT_NAME} ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp)

target_link_libraries(${PROJECT_NAME} PRIVATE sgg::sgg)
```

When trying to run a clean build I get the following output:

```
====================[ Build | 1942_berlin | Debug ]=============================
/home/ilias/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.8194.17/bin/cmake/linux/bin/cmake --build "/home/ilias/Programs/JetBrains Projects/CLionProjects/1942_berlin/cmake-build-debug" --target 1942_berlin -- -j 6
gmake[3]: *** No rule to make target '/home/ilias/sgg/build/libsgg.a', needed by '1942_berlin'.  Stop.
gmake[3]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/1942_berlin.dir/src/main.cpp.o
gmake[2]: *** [CMakeFiles/Makefile2:96: CMakeFiles/1942_berlin.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:103: CMakeFiles/1942_berlin.dir/rule] Error 2
gmake: *** [Makefile:138: 1942_berlin] Error 2
```

The fix to this was to build the library using `sh ~/sgg/build_sgg_x64.sh` and then copy the libsgg.a and libsggd.a from ~/sgg/lib to ~/sgg/build using `cp ~/sgg/lib/libsgg.a ~/sgg/build/libsgg.a && ~/sgg/lib/libsggd.a ~/sgg/build/libsggd.a`.

Finally, the output, as requested, from `VERBOSE=1 cmake --build build` was `Error: /home/ilias/sgg/build is not a directory` (before I ran the build script) and `Error: could not load cache` (after I ran the build script). 

My pleasure to help as much as my knowledge allows.

Kind regards.

**Comment by iliaskap12** [comment]
__*UPDATE*__

I realized I run the wrong cmake command with VERBOSE=1. Below is the set of commands I ran and their respective output:

*The commands (without building the library):*
```
$ cd
$ sudo rm -r sgg/build
$ sudo rm -r sgg/lib/
$ cd sgg
$ VERBOSE=1 cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_PACKAGE_REGISTRY=ON -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
$ sudo find ~/sgg/ -iname "*libsgg*"
```
*The output:*
```
Re-run cmake no build system arguments
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ilias/sgg/build
```
(nothing outputted by the find command)

*The commands (with building the library):*
```
$ cd
$ sudo rm -r sgg/build
$ sudo rm -r sgg/lib/
$ cd sgg
$ sh ./build_sgg_x64.sh
$ VERBOSE=1 cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_PACKAGE_REGISTRY=ON -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
$ sudo find ~/sgg/ -iname "*libsgg*"
```

*The output:*
(output from build script)
```
In file included from /usr/include/stdio.h:866,
                 from sgg/audio.cpp:20:
In function ‘int fprintf(FILE*, const char*, ...)’,
    inlined from ‘Audio* createAudio(const char*, uint8_t, int)’ at sgg/audio.cpp:253:16:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:103:24: warning: ‘%s’ directive argument is null [-Wformat-overflow=]
  103 |   return __fprintf_chk (__stream, __USE_FORTIFY_LEVEL - 1, __fmt,
      |          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  104 |    __va_arg_pack ());
      |    ~~~~~~~~~~~~~~~~~    
```
(output from cmake)
```
Re-run cmake no build system arguments
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ilias/sgg/build
```
(output from find)
```
/home/ilias/sgg/lib/libsggd.a
/home/ilias/sgg/lib/libsgg.a
```

**Comment by liarokapisv** [comment]
Hi ilias, you made me realize we need to make some things clearer in the Docs. The build scripts are not needed for the cmake integration. They are in the repository as alternative ways to build the libraries. You shouldn't have to deal with them when using cmake for building.

As for the above problems, it appears you are not building after configuring the project. 
This is a two-step process:

1. You first need to configure the project:
```
cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_PACKAGE_REGISTRY=ON -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
```

2. Then you need to actually build it:
```
cmake --build build
```

If you need any further help feel free to contact me at `liarokapis.v@gmail.com`

**Comment by iliaskap12** [comment]
Perfect, that solved the problem. I thought the building process was required by option 2 only, my mistake. Thanks a lot for the help. I hope at least I helped with the docs. Kind regards.

**Comment by liarokapisv** [comment]
I improved the README in order to highlight required steps and prevent the issues that @iliaskap12  had.

**Comment by liarokapisv** [comment]
Just checking to see if everything is alright. Any plans to integrate the patch this semester?

**Comment by ViNeek** [comment]
> 
> 
> Just checking to see if everything is alright. Any plans to integrate the patch this semester?

Yes, we definitely have plans to merge CMake support for the next semester. Thanks again for the pull request.

**Pull request merged**
