### PR TITLE
Implementation of macOS support 

### PR DESCRIPTION
**Pull request by gsiros**
- Added macOS shell script installers for the library and the demos (both release and debug).
- **Fixed**; SDL2 'include' bug regarding `memset_pattern4` causing the compilation of `sgg` to fail in macOS.

### CODE REVIEW

**Review by ViNeek — CHANGES_REQUESTED** [review]
Please clear the pull request from the .DS_Store files. Add a .gitignore if needed.
Also let's leave the Instructions file outside of the commit. We will add them straight to the documentation.

**Comment by gsiros** [comment]
Repo cleaned from .DS_Store native files. Removed the instructions manual as well. Should be all good by now.

**Comment by ViNeek** [comment]
Thanks @gsiros! Very nice work.

**Review by ViNeek — COMMENTED** [review]
Looks good!

**Pull request merged**
